# Generated by Django 4.1.4 on 2023-06-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="formtable", name="passportPhotoName",),
        migrations.RemoveField(model_name="formtable", name="signOfParentName",),
        migrations.RemoveField(model_name="formtable", name="signOfStudentName",),
    ]
