# Generated by Django 4.1.4 on 2023-06-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_formtable_passportphotoname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formtable",
            name="docs",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
